version: '4'
networks:
  mynetwork:
    driver: bridge
    name : NetworkAOI
services:
  mysql:
    image: mysql:latest
    restart: on-failure
    env_file:
      - local.env
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - mynetwork


      